"""Markdown renderer for `praxis skills extract`. Lists prompt clusters with
pairwise similarities and a suggested action per cluster."""

from __future__ import annotations

from praxis_core.extract.prompts import PromptCluster


def render_extract_report(
    clusters: list[PromptCluster],
    threshold: float,
    total_prompts: int,
) -> str:
    lines: list[str] = []
    lines.append("# Skills extract report")
    lines.append("")
    lines.append(f"- **Prompts scanned:** {total_prompts}")
    lines.append(f"- **Similarity threshold:** {threshold:.2f} (Jaccard on token bigrams)")
    lines.append(f"- **Clusters found:** {len(clusters)}")
    lines.append("")

    if not clusters:
        lines.append("No prompt clusters above threshold. Nothing to extract.")
        lines.append("")
        lines.append("_Generated by Praxis v0.2 (skills extract)._")
        return "\n".join(lines)

    lines.append("Each cluster is a candidate for consolidation into a single Hermes skill")
    lines.append("with parameterized inputs. Review the pairwise scores below — a near-1.0")
    lines.append("score means the prompts differ only in their interpolated variables.")
    lines.append("")

    for i, cluster in enumerate(clusters, start=1):
        lines.append(f"## Cluster {i} — {cluster.size} prompts")
        lines.append("")
        lines.append("**Members:** " + ", ".join(f"`{m}`" for m in cluster.members))
        lines.append("")
        lines.append(
            f"**Similarity range:** {cluster.min_similarity:.2f} – {cluster.max_similarity:.2f}"
        )
        lines.append("")
        lines.append("**Pairwise scores:**")
        lines.append("")
        lines.append("| A | B | Jaccard |")
        lines.append("|---|---|--------:|")
        for (a, b), s in sorted(cluster.pairwise.items()):
            lines.append(f"| `{a}` | `{b}` | {s:.2f} |")
        lines.append("")
        lines.append(f"**Suggested action:** {_suggested_action(cluster)}")
        lines.append("")

    lines.append("_Generated by Praxis v0.2 (skills extract)._")
    return "\n".join(lines)


def _suggested_action(cluster: PromptCluster) -> str:
    if cluster.min_similarity >= 0.85:
        return (
            "Near-duplicate prompts — merge into one skill and parameterize the differing "
            "variables. Delete the redundant prompt files."
        )
    if cluster.min_similarity >= 0.6:
        return (
            "Strong structural overlap — likely one skill with two prose variants. "
            "Consider extracting common preamble; keep distinct task-specific tails."
        )
    return (
        "Loose family resemblance — review before merging. May share a common framing "
        "but serve genuinely different tasks."
    )
