"""Markdown renderer for `praxis skills extract`. Lists prompt clusters with
pairwise similarities and a suggested action per cluster, plus repeated
tool sequences across workflows."""

from __future__ import annotations

from praxis_core.extract.prompts import PromptCluster
from praxis_core.extract.sequences import RepeatedSequence


def render_extract_report(
    clusters: list[PromptCluster],
    threshold: float,
    total_prompts: int,
    sequences: list[RepeatedSequence] | None = None,
    total_workflows: int = 0,
) -> str:
    sequences = sequences or []
    lines: list[str] = []
    lines.append("# Skills extract report")
    lines.append("")
    lines.append(f"- **Prompts scanned:** {total_prompts}")
    lines.append(f"- **Workflows scanned:** {total_workflows}")
    lines.append(f"- **Similarity threshold:** {threshold:.2f} (Jaccard on token bigrams)")
    lines.append(f"- **Prompt clusters found:** {len(clusters)}")
    lines.append(f"- **Repeated tool sequences found:** {len(sequences)}")
    lines.append("")

    lines.append("## Prompt clusters")
    lines.append("")
    if not clusters:
        lines.append("No prompt clusters above threshold.")
        lines.append("")
    else:
        _render_prompt_clusters(lines, clusters)

    lines.append("## Repeated tool sequences")
    lines.append("")
    if not sequences:
        lines.append(
            "No tool sequences of length ≥ 2 recur across ≥ 2 workflows. Nothing to factor out."
        )
        lines.append("")
    else:
        _render_sequence_section(lines, sequences)

    lines.append("_Generated by Praxis v0.2 (skills extract)._")
    return "\n".join(lines)


def _render_prompt_clusters(lines: list[str], clusters: list[PromptCluster]) -> None:
    lines.append("Each cluster is a candidate for consolidation into a single Hermes skill")
    lines.append("with parameterized inputs. Review the pairwise scores below — a near-1.0")
    lines.append("score means the prompts differ only in their interpolated variables.")
    lines.append("")

    for i, cluster in enumerate(clusters, start=1):
        lines.append(f"### Cluster {i} — {cluster.size} prompts")
        lines.append("")
        lines.append("**Members:** " + ", ".join(f"`{m}`" for m in cluster.members))
        lines.append("")
        lines.append(
            f"**Similarity range:** {cluster.min_similarity:.2f} – {cluster.max_similarity:.2f}"
        )
        lines.append("")
        lines.append("**Pairwise scores:**")
        lines.append("")
        lines.append("| A | B | Jaccard |")
        lines.append("|---|---|--------:|")
        for (a, b), s in sorted(cluster.pairwise.items()):
            lines.append(f"| `{a}` | `{b}` | {s:.2f} |")
        lines.append("")
        lines.append(f"**Suggested action:** {_prompt_suggested_action(cluster)}")
        lines.append("")


def _render_sequence_section(lines: list[str], sequences: list[RepeatedSequence]) -> None:
    lines.append("Each sequence is a tool chain that appears verbatim in multiple workflows.")
    lines.append("Strong candidates to factor into a single named Hermes skill.")
    lines.append("")

    for i, seq in enumerate(sequences, start=1):
        chain = " → ".join(f"`{t}`" for t in seq.tools)
        lines.append(f"### Sequence {i} — length {seq.length}, in {seq.occurrences} workflows")
        lines.append("")
        lines.append(f"**Chain:** {chain}")
        lines.append("")
        lines.append("**Appears in:** " + ", ".join(f"`{w}`" for w in seq.workflows))
        lines.append("")
        lines.append(f"**Suggested action:** {_sequence_suggested_action(seq)}")
        lines.append("")


def _prompt_suggested_action(cluster: PromptCluster) -> str:
    if cluster.min_similarity >= 0.85:
        return (
            "Near-duplicate prompts — merge into one skill and parameterize the differing "
            "variables. Delete the redundant prompt files."
        )
    if cluster.min_similarity >= 0.6:
        return (
            "Strong structural overlap — likely one skill with two prose variants. "
            "Consider extracting common preamble; keep distinct task-specific tails."
        )
    return (
        "Loose family resemblance — review before merging. May share a common framing "
        "but serve genuinely different tasks."
    )


def _sequence_suggested_action(seq: RepeatedSequence) -> str:
    if seq.length >= 4 or seq.occurrences >= 3:
        return (
            "Strong factor-out candidate — define one Hermes skill that captures this chain "
            "and call it from each workflow rather than inlining the steps."
        )
    return (
        "Possible factor-out — review whether these workflows share intent or just coincidentally "
        "call the same tools in the same order."
    )
