"""Markdown migration report. Per-node feasibility, blockers, and TODOs."""

from __future__ import annotations

from collections import Counter

from praxis_core.ir import IRGraph
from praxis_core.ir.models import Node, NodeKind, PortabilityTier


def render_migration_report(ir: IRGraph) -> str:
    lines: list[str] = []
    lines.append("# Migration report")
    lines.append("")
    project = ir.project
    if project:
        lines.append(f"- **Project:** `{project.name}`")
        lines.append(f"- **Source framework:** `{project.source_framework}`")
        lines.append(f"- **Source root:** `{project.source_root}`")
        if project.analyzed_at:
            lines.append(f"- **Analyzed at:** `{project.analyzed_at.isoformat()}`")
        lines.append("")

    lines += _summary(ir)
    lines += _node_table(ir)
    lines += _todos(ir)
    lines += _env_section(ir)
    lines += _services_section(ir)
    lines += _diagnostics(ir)
    lines.append("")
    lines.append("_Generated by Praxis v0.1._")
    return "\n".join(lines)


def _summary(ir: IRGraph) -> list[str]:
    tiers: Counter[str] = Counter()
    for n in ir.nodes:
        if n.portability:
            tier = (
                n.portability.tier
                if isinstance(n.portability.tier, str)
                else n.portability.tier.value
            )
            tiers[tier] += 1
    total = sum(tiers.values()) or 1
    portable = tiers.get(PortabilityTier.PORTABLE.value, 0)
    out = ["## Summary", ""]
    out.append(f"- Total scored nodes: **{total}**")
    out.append(f"- Portable: **{portable}** ({portable * 100 // total}%)")
    out.append(f"- Partial: **{tiers.get(PortabilityTier.PARTIAL.value, 0)}**")
    out.append(f"- Needs review: **{tiers.get(PortabilityTier.NEEDS_REVIEW.value, 0)}**")
    out.append(f"- Unsupported: **{tiers.get(PortabilityTier.UNSUPPORTED.value, 0)}**")
    out.append("")
    return out


def _node_table(ir: IRGraph) -> list[str]:
    out = [
        "## Per-node feasibility",
        "",
        "| Kind | Name | Tier | Score | Rationale |",
        "|---|---|---|---|---|",
    ]
    for n in sorted(ir.nodes, key=lambda x: (_kind(x), x.name)):
        if not n.portability:
            continue
        tier = (
            n.portability.tier if isinstance(n.portability.tier, str) else n.portability.tier.value
        )
        rationale = (n.portability.rationale or "").replace("|", "\\|")
        out.append(
            f"| `{_kind(n)}` | `{n.name}` | {tier} | {n.portability.score:.2f} | {rationale} |"
        )
    out.append("")
    return out


def _todos(ir: IRGraph) -> list[str]:
    todos: list[tuple[str, str, list[str]]] = []
    for n in ir.nodes:
        if n.portability and n.portability.blockers:
            todos.append((_kind(n), n.name, n.portability.blockers))
    if not todos:
        return ["## TODOs", "", "_No blocking review items._", ""]
    out = ["## TODOs", ""]
    for kind, name, blockers in todos:
        out.append(f"### `{kind}` `{name}`")
        for b in blockers:
            out.append(f"- {b}")
        out.append("")
    return out


def _env_section(ir: IRGraph) -> list[str]:
    envs = [n.name for n in ir.nodes if _kind(n) == NodeKind.ENV.value]
    if not envs:
        return []
    out = ["## Required environment", "", "Set these on the Hermes side:", ""]
    for v in sorted(envs):
        out.append(f"- `{v}`")
    out.append("")
    return out


def _services_section(ir: IRGraph) -> list[str]:
    services = [n for n in ir.nodes if _kind(n) == NodeKind.SERVICE.value]
    if not services:
        return []
    out = [
        "## External services",
        "",
        "Declared in OpenClaw — wire equivalents on the Hermes side:",
        "",
        "| Service | Kind | Notes |",
        "|---|---|---|",
    ]
    for s in services:
        spec = (s.metadata or {}).get("spec") or {}
        out.append(
            f"| `{s.name}` | `{spec.get('kind', '?')}` | `{spec.get('base_url') or spec.get('dsn') or ''}` |"
        )
    out.append("")
    return out


def _diagnostics(ir: IRGraph) -> list[str]:
    if not ir.diagnostics:
        return []
    out = ["## Diagnostics", "", "| Level | Code | Message |", "|---|---|---|"]
    for d in ir.diagnostics:
        msg = d.message.replace("|", "\\|")
        out.append(f"| {d.level} | {d.code or ''} | {msg} |")
    out.append("")
    return out


def _kind(n: Node) -> str:
    return n.kind if isinstance(n.kind, str) else n.kind.value
